services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tokenvesting_mvp
    ports:
      - "5432:5432"

  web:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npm install &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run dev -- -H 0.0.0.0
      "
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/tokenvesting_mvp
    depends_on:
      - db